// <auto-generated />
namespace Datas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Identity21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identity21));
        
        string IMigrationMetadata.Id
        {
            get { return "201501201417210_Identity2.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
