//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionPrize
    {
        public string RoundKey { get; set; }
        public string PrizeName { get; set; }
        public int CompetitionId { get; set; }
        public int Id { get; set; }
    }
}
