//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Competition
{
    public int Id { get; set; }
    public string Type { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public string Name { get; set; }
}

public partial class Money
{
    public string User { get; set; }
    public int Money1 { get; set; }
}

public partial class Order
{
    public int Id { get; set; }
    public string User { get; set; }
    public System.DateTime Date { get; set; }
    public string Team { get; set; }
    public int Quantity { get; set; }
    public int Status { get; set; }
    public int Price { get; set; }
    public string Side { get; set; }
    public int IdUniverseCompetition { get; set; }
}

public partial class Result
{
    public string Team { get; set; }
    public int Value { get; set; }
}

public partial class Team
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int IdCompetition { get; set; }
    public Nullable<int> Result { get; set; }
}

public partial class Trade
{
    public int Id { get; set; }
    public string Buyer { get; set; }
    public string Seller { get; set; }
    public System.DateTime Date { get; set; }
    public string Team { get; set; }
    public int Quantity { get; set; }
    public int Price { get; set; }
    public int IdUniverseCompetition { get; set; }
}

public partial class Universe
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string AdminUser { get; set; }
}

public partial class UniverseAvailable
{
    public int Id { get; set; }
    public int IdUniverse { get; set; }
    public string UserName { get; set; }
}

public partial class UniverseCompetition
{
    public int IdUniverse { get; set; }
    public int IdCompetition { get; set; }
    public int Id { get; set; }
}
