//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;
using System.Linq;

namespace Datas.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base(GetConnectionString())
        {
        }

        private static string GetConnectionString()
        {
            var uriString = ConfigurationManager.AppSettings["SQLSERVER_URI"];
            var uri = new Uri(uriString);

            // Initialize the connection string builder for the
            // underlying provider.
            SqlConnectionStringBuilder sqlBuilder =
            new SqlConnectionStringBuilder();

            // Set the properties for the data source.
            sqlBuilder.DataSource = uri.Host;
            sqlBuilder.InitialCatalog = uri.AbsolutePath.Trim('/');
            sqlBuilder.UserID = uri.UserInfo.Split(':').First();
            sqlBuilder.Password = uri.UserInfo.Split(':').Last();
            sqlBuilder.PersistSecurityInfo = true;
            sqlBuilder.MultipleActiveResultSets = true;
            sqlBuilder.ApplicationName = "EntityFramework";

            // Build the SqlConnection connection string.
            string providerString = sqlBuilder.ToString();

            // Initialize the EntityConnectionStringBuilder.
            EntityConnectionStringBuilder entityBuilder =
            new EntityConnectionStringBuilder();

            //Set the provider name.
            entityBuilder.Provider = "System.Data.SqlClient";

            // Set the provider-specific connection string.
            entityBuilder.ProviderConnectionString = providerString;

            // Set the Metadata location.
            entityBuilder.Metadata = @"res://*/Entities.BetModel.csdl|res://*/Entities.BetModel.ssdl|res://*/Entities.BetModel.msl";
            return entityBuilder.ToString();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Money> Moneys { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Trade> Trades { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Universe> Universes { get; set; }
        public virtual DbSet<UniverseCompetition> UniverseCompetitions { get; set; }
        public virtual DbSet<UniverseAvailable> UniverseAvailables { get; set; }
    }
}
