//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwapOrder
    {
        public int Id { get; set; }
        public string User { get; set; }
        public System.DateTime Date { get; set; }
        public int BuyTeam { get; set; }
        public int BuyQuantity { get; set; }
        public int SellTeam { get; set; }
        public int SellQuantity { get; set; }
        public int Status { get; set; }
        public int Price { get; set; }
        public int IdUniverseCompetition { get; set; }
    }
}
