//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Datas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        [XmlIgnore]
        public string Name { get; set; }
        [XmlIgnore]
        public int IdCompetition { get; set; }
        [XmlIgnore]
        public Nullable<int> Result { get; set; }
        [XmlIgnore]
        public Nullable<bool> RealTeam { get; set; }
        [XmlIgnore]
        public Nullable<double> Strength { get; set; }
    }
}
