//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datas.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public string Buyer { get; set; }
        public string Seller { get; set; }
        public System.DateTime Date { get; set; }
        public string Team { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
        public int IdUniverseCompetition { get; set; }
    }
}
